version: "2"

services:
  postgres:
    image: postgres:9.5
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

  www:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - "./:/www"

